### ISSUE TITLE
Why is the "fused" module missing?

### ISSUE THREAD

**Issue by an-zi-li** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#32]
I have installed torch==1.5.1 CUDA ==10.1 as you requested, but the following problems still occur

D:\anaconda\envs\torch151\python.exe D:/pycharm_workspace/Files/stylegan2/inference/inference.py
Traceback (most recent call last):
  File "D:/pycharm_workspace/Files/stylegan2/inference/inference.py", line 4, in <module>
    from megafs import resnet50, HieRFE, Generator, FaceTransferModule
  File "D:\pycharm_workspace\Files\stylegan2\inference\megafs.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "D:\pycharm_workspace\Files\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "D:\pycharm_workspace\Files\stylegan2\op\fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "D:\anaconda\envs\torch151\lib\site-packages\torch\utils\cpp_extension.py", line 921, in load
    is_python_module)
  File "D:\anaconda\envs\torch151\lib\site-packages\torch\utils\cpp_extension.py", line 1120, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\anaconda\envs\torch151\lib\site-packages\torch\utils\cpp_extension.py", line 1441, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\anaconda\envs\torch151\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by zyainfal** [comment]
It seems rosinality has changed the file `fused_act.py `. 
You can find the version I used in my forked repositories [here](https://github.com/zyainfal/stylegan2-pytorch).

**Comment by an-zi-li** [comment]
> 



> 似乎 rosinality 改变了文件`fused_act.py `。[您可以在此处](https://github.com/zyainfal/stylegan2-pytorch) 找到我在分叉存储库中使用的版本。[](https://github.com/zyainfal/stylegan2-pytorch)

Hi, I have looked at some of the libraries, but I find that my problem is still not found in the solution

**Comment by zyainfal** [comment]
I noticed that
`File "D:\pycharm_workspace\Files\stylegan2\op\fused_act.py", line 15, in
os.path.join(module_path, "fused_bias_act_kernel.cu"),`
as you used Windows OS, may this `module_path` is not same as it in Linux?

And every step the script searches files may suffer from this issue, like the `[path]` in
`File "D:\anaconda\envs\torch151\lib\site-packages\torch\utils\cpp_extension.py", line 1441, in _import_module_from_library
file, path, description = imp.find_module(module_name, [path])`

**Comment by an-zi-li** [comment]
> I noticed that `File "D:\pycharm_workspace\Files\stylegan2\op\fused_act.py", line 15, in os.path.join(module_path, "fused_bias_act_kernel.cu"),` as you used Windows OS, may this `module_path` is not same as it in Linux?
> 
> And every step the script searches files may suffer from this issue, like the `[path]` in `File "D:\anaconda\envs\torch151\lib\site-packages\torch\utils\cpp_extension.py", line 1441, in _import_module_from_library file, path, description = imp.find_module(module_name, [path])`

Thank you for your reply. Now this problem has been solved. The specific method is in the link：[https://animadversio.github.io/tech_note/debugging-stylegan2](url)

**Comment by zyainfal** [comment]
Sounds Great!
