### ISSUE TITLE
ModuleNotFoundError: No module named 'op'

### ISSUE THREAD

**Issue by PostgraduateWeiCao** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#33]
Traceback (most recent call last):
  File "inference.py", line 4, in <module>
    from megafs import resnet50, HieRFE, Generator, FaceTransferModule
  File "D:\pycharm\faceSwap_project\One-Shot-Face-Swapping-on-Megapixels-main\inference\megafs.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
ModuleNotFoundError: No module named 'op'

**Comment by Georgefwt** [comment]
you should find 'op' in stylegan2-pytorch

**Comment by PostgraduateWeiCao** [comment]
thanks! I found it
