### ISSUE TITLE
ImportError: No module named 'fused'?

### ISSUE THREAD

**Issue by postcw** [zyainfal/One-Shot-Face-Swapping-on-Megapixels#34]
Traceback (most recent call last):
  File "inference.py", line 4, in <module>
    from megafs import resnet50, HieRFE, Generator, FaceTransferModule
  File "/root/data/deepfake_Generate_Comparative_Experiment/One-Shot-Face-Swapping-on-Megapixels-main/inference/megafs.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/root/data/deepfake_Generate_Comparative_Experiment/One-Shot-Face-Swapping-on-Megapixels-main/inference/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/root/data/deepfake_Generate_Comparative_Experiment/One-Shot-Face-Swapping-on-Megapixels-main/inference/op/fused_act.py", line 16, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/opt/conda/envs/Mega/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/opt/conda/envs/Mega/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/opt/conda/envs/Mega/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/opt/conda/envs/Mega/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by zyainfal** [comment]
see issue #32

**Comment by postcw** [comment]
Sorry, I looked at question #32 and I still couldn't find how to fix this. Question 32 is for windows, I am running on linux, don't know if you have encountered this before?

**Comment by zyainfal** [comment]
I didn't encounter this problem before, but https://animadversio.github.io/tech_note/debugging-stylegan2 does give a Linux solution, you may want to check it.
